export const ActionTypes = {
  //loginRequest
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_REQUEST_SUCCESS: 'LOGIN_REQUEST_SUCCESS',
  LOGIN_REQUEST_FAILURE: 'LOGIN_REQUEST_FAILURE',
  LOG_OUT_REQUEST: 'LOG_OUT_REQUEST',
  RESTART_LOGIN_REQUEST:"RESTART_LOGIN_REQUEST",

  //VERIFY
  VERIFY_REQUEST: 'VERIFY_REQUEST',
  VERIFY_REQUEST_SUCCESS: 'VERIFY_REQUEST_SUCCESS',
  VERIFY_REQUEST_FAILURE: 'VERIFY_REQUEST_FAILURE',

  //  REGISTER USER
  REGISTER_USER_REQUEST: 'REGISTER_USER_REQUEST',
  REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
  REGISTER_USER_FAILURE: 'REGISTER_USER_FAILURE',

  //UPDATE_PASSWORD
  UPDATE_PASSWORD_REQUEST:"UPDATE_PASSWORD_REQUEST",
  UPDATE_PASSWORD_SUCCESS:"UPDATE_PASSWORD_SUCCESS",
  UPDATE_PASSWORD_FAUILURE:"UPDATE_PASSWORD_FAUILURE",

  FETCH_USERPROFILE_REQUEST: 'FETCH_USERPROFILE_REQUEST',
  FETCH_USERPROFILE_SUCCESS: 'FETCH_USERPROFILE_SUCCESS',
  FETCH_USERPROFILE_FAILURE: 'FETCH_USERPROFILE_FAILURE',

  UPDATE_USERPROFILE_REQUEST: "UPDATE_USERPROFILE_REQUEST",
  UPDATE_USERPROFILE_SUCCESS: "UPDATE_USERPROFILE_SUCCESS",
  UPDATE_USERPROFILE_FAILURE: "UPDATE_USERPROFILE_FAILURE",

  //FETCH_CATEGORIES_REQUEST
  FETCH_CATEGORIES_REQUEST: 'FETCH_CATEGORIES_REQUEST',
  FETCH_CATEGORIES_SUCCESS: 'FETCH_CATEGORIES_SUCCESS',
  FETCH_CATEGORIES_FAILURE: 'FETCH_CATEGORIES_FAILURE',

  FETCH_BESTSELLER_REQUEST: 'FETCH_BESTSELLER_REQUEST',
  FETCH_BESTSELLER_SUCCESS: 'FETCH_BESTSELLER_SUCCESS',
  FETCH_BESTSELLER_FAILURE: 'FETCH_BESTSELLER_FAILURE',

  //FETCH_COMBO_REQUEST
  FETCH_COMBO_REQUEST: 'FETCH_COMBO_REQUEST',
  FETCH_COMBO_SUCCESS: 'FETCH_COMBO_SUCCESS',
  FETCH_COMBO_FAILURE: 'FETCH_COMBO_FAILURE',

  //FETCH_BANNER_REQUEST
  FETCH_BANNER_REQUEST: 'FETCH_BANNER_REQUEST',
  FETCH_BANNER_SUCCESS: 'FETCH_BANNER_SUCCESS',
  FETCH_BANNER_FAILURE: 'FETCH_BANNER_FAILURE',

  //FETCH_SOCIAL_MEDIA_REQUEST
  FETCH_SOCIAL_MEDIA_REQUEST: 'FETCH_SOCIAL_MEDIA_REQUEST',
  FETCH_SOCIAL_MEDIA_SUCCESS: 'FETCH_SOCIAL_MEDIA_SUCCESS',
  FETCH_SOCIAL_MEDIA_FAILURE: 'FETCH_SOCIAL_MEDIA_FAILURE',

  // ProductsWithPricing
  PRODUCT_PRICE_REQUEST: 'PRODUCT_PRICE_REQUEST',
  PRODUCT_PRICE_SUCCESS: 'PRODUCT_PRICE_SUCCESS',
  PRODUCT_PRICE_FAILURE: 'PRODUCT_PRICE_FAILURE',
  
  // PRODUCT_BYID__REQUEST
  PRODUCT_BYID__REQUEST: 'PRODUCT_BYID__REQUEST',
  PRODUCT_BYID__SUCCESS: 'PRODUCT_BYID__SUCCESS',
  PRODUCT_BYID__FAILURE: 'PRODUCT_BYID__FAILURE',

  // CART
  FETCH_CART_REQUEST: 'FETCH_CART_REQUEST',
  FETCH_CART_SUCCESS: 'FETCH_CART_SUCCESS',
  FETCH_CART_FAILURE: 'FETCH_CART_FAILURE',

  // FETCH_ORDER_REQUEST
  FETCH_ORDER_REQUEST: 'FETCH_ORDER_REQUEST',
  FETCH_ORDER_SUCCESS: 'FETCH_ORDER_SUCCESS',
  FETCH_ORDER_FAILURE: 'FETCH_ORDER_FAILURE',

  // FETCH_COUPON_REQUEST

  FETCH_COUPON_REQUEST: 'FETCH_COUPON_REQUEST',
  FETCH_COUPON_SUCCESS: 'FETCH_COUPON_SUCCESS',
  FETCH_COUPON_FAILURE: 'FETCH_COUPON_FAILURE',

  APPLY_COUPON_REQUEST:"APPLY_COUPON_REQUEST",
  APPLY_COUPON_SUCCESS:"APPLY_COUPON_SUCCESS",
  APPLY_COUPON_FAILURE:"APPLY_COUPON_FAILURE",

  APPLY_ADDRESS_REQUEST:"APPLY_ADDRESS_REQUEST",
  APPLY_ADDRESS_SUCCESS:"APPLY_ADDRESS_SUCCESS",
  APPLY_ADDRESS_FAILURE:"APPLY_ADDRESS_FAILURE",

  ADD_CART_REQUEST: 'ADD_CART_REQUEST',
  ADD_CART_SUCCESS: 'ADD_CART_SUCCESS',
  ADD_CART_FAILURE: 'ADD_CART_FAILURE',

  REMOVE_CART_REQUEST: 'REMOVE_CART_REQUEST',
  REMOVE_CART_SUCCESS: 'REMOVE_CART_SUCCESS',
  REMOVE_CART_FAILURE: 'REMOVE_CART_FAILURE',

  UPDATE_CART_REQUEST: "UPDATE_CART_REQUEST",
  UPDATE_CART_SUCCESS: "UPDATE_CART_SUCCESS",
  UPDATE_CART_FAILURE: "UPDATE_CART_FAILURE",


  //Check User Location
  CHECK_LOCATION_REQUEST: "CHECK_LOCATION_REQUEST",
  CHECK_LOCATION_SUCCESS: "CHECK_LOCATION_SUCCESS",
  CHECK_LOCATION_FAILURE: "CHECK_LOCATION_FAILURE",

  //GET_LOCATION_REQUEST
  GET_LOCATION_REQUEST: "GET_LOCATION_REQUEST",
  GET_LOCATION_SUCCESS: "GET_LOCATION_SUCCESS",
  GET_LOCATION_FAILURE: "GET_LOCATION_FAILURE",



  // //USER PROFILE
  // FETCH_PROFILE_REQUEST:"FETCH_PROFILE_REQUEST",
  // FETCH_PROFILE_SUCCESS:"FETCH_PROFILE_SUCCESS",
  // FETCH_PROFILE_FAILURE:"FETCH_PROFILE_FAILURE",

  // //SEARCH_PROFILE_
  // SEARCH_PROFILE_REQUEST:"SEARCH_PROFILE_REQUEST",
  // SEARCH_PROFILE_SUCCESS:"SEARCH_PROFILE_SUCCESS",
  // SEARCH_PROFILE_FAILURE:"SEARCH_PROFILE_FAILURE",

  // // FETCH_FOLLOWER_
  // FETCH_FOLLOWER_REQUEST:"FETCH_FOLLOWER_REQUEST",
  // FETCH_FOLLOWER_SUCCESS:"FETCH_FOLLOWER_SUCCESS",
  // FETCH_FOLLOWER_FAILURE:"FETCH_FOLLOWER_FAILURE",

  // // FETCH_PROFILE_:"FETCH_PROFILE_",
  // UPDATE_PROFILE_REQUEST:"UPDATE_PROFILE_REQUEST",
  // UPDATE_PROFILE_SUCCESS:"UPDATE_PROFILE_SUCCESS",
  // UPDATE_PROFILE_FAILURE:"UPDATE_PROFILE_FAILURE",

  // UPDATE_PASSWORD_REQUEST:"UPDATE_PASSWORD_REQUEST",
  // UPDATE_PASSWORD_SUCCESS:"UPDATE_PASSWORD_SUCCESS",
  // UPDATE_PASSWORD_FAILURE:"UPDATE_PASSWORD_FAILURE",

  // // CHECK_SESSION
  // CHECK_SESSION:"CHECK_SESSION",
  // CHECK_SESSION_SUCCESS:"CHECK_SESSION_SUCCESS",
  // CHECK_SESSION_FAILURE:"CHECK_SESSION_FAILURE",

  // //Fectch restaurants
  // // FETCH_NOTIFICATION_
  // FETCH_NOTIFICATION_REQUEST:"FETCH_NOTIFICATION_REQUEST",
  // FETCH_NOTIFICATION_SUCCESS: 'FETCH_NOTIFICATION_SUCCESS',
  // FETCH_NOTIFICATION_FAILURE: 'FETCH_NOTIFICATION_FAILURE',

  // FETCH_USERBYID_REQUEST: 'FETCH_USERBYID_REQUEST',
  // FETCH_USERBYID_SUCCESS:"FETCH_USERBYID_SUCCESS",
  // FETCH_USERBYID_FAILURE:"FETCH_USERBYID_FAILURE",

  // FORGET_PASSWORD:"FORGET_PASSWORD",
  // FORGET_PASSWORD_SUCCESS:"FORGET_PASSWORD_SUCCESS",
  // FORGET_PASSWORD_FAILURE:"FORGET_PASSWORD_FAILURE",

  // RESET_PASSWORD:"RESET_PASSWORD",
  // RESET_PASSWORD_SUCCESS:"RESET_PASSWORD_SUCCESS",
  // RESET_PASSWORD_FAILURE:"RESET_PASSWORD_FAILURE",

  // FOLLOW_UNFOLLOW_REQUEST:"FOLLOW_UNFOLLOW_REQUEST",
  // FOLLOW_UNFOLLOW_SUCCESS:"FOLLOW_UNFOLLOW_SUCCESS",
  // FOLLOW_UNFOLLOW_FAILURE:"FOLLOW_UNFOLLOW_FAILURE",

  // ADD_TO_CARD: 'ADD_TO_CARD',
  // REMOVE_FROM_CARD: 'REMOVE_FROM_CARD',

  //   ADD_TO_WISHLIST: 'ADD_TO_WISHLIST',
  //   REMOVE_FROM_WISHLIST: 'REMOVE_FROM_WISHLIST',
  //   CHANGE_THEME: 'CHANGE_THEME',
  //   START_LOADING: 'START_LOADING',
  //   STOP_LOADING: 'STOP_LOADING',
  //   SELECT_LANGUAGE: 'SELECT_LANGUAGE',
  //   PRODUCT_LIST: 'PRODUCT_LIST',
  //   SET_PRODUCT_LIST: 'SET_PRODUCT_LIST',
  //   USER_LIST: 'USER_LIST',
  //   SET_USER_LIST: 'SET_USER_LIST',

  //   GET_PROFILE:"GET_PROFILE",
  //   SET_PROFILE:"SET_PROFILE",
  //   FAILURE_PROFILE:"FAILURE_PROFILE",
  //   UPDATE_PROFILE_ACCESS_TOKEN: 'UPDATE_PROFILE_ACCESS_TOKEN',
};
